### ISSUE TITLE
Compatibility with hardhat-deploy

### ISSUE THREAD

**Issue by mshakeg** [hashgraph/hedera-hardhat-hethers#28]
### Problem

[hardhat-deploy](https://www.npmjs.com/package/hardhat-deploy) doesn't work with `@hashgraph/hardhat-hethers`.
Attempting `await deployments.fixtures()` results in the following error stack trace:
```
TypeError: this.network.provider.send is not a function
      at DeploymentsManager.getChainId (node_modules/hardhat-deploy/src/DeploymentsManager.ts:443:51)
      at DeploymentsManager.loadDeployments (node_modules/hardhat-deploy/src/DeploymentsManager.ts:619:28)
      at DeploymentsManager.runDeploy (node_modules/hardhat-deploy/src/DeploymentsManager.ts:998:16)
      at Object.fixture (node_modules/hardhat-deploy/src/DeploymentsManager.ts:315:20)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async initialize (test/helpers.ts:40:3)
      at async Context.<anonymous> (test/_/Contract.test.ts:10:5)
```

### Solution

- In [hardhat-deploy](https://www.npmjs.com/package/hardhat-deploy) the DeploymentsManager's constructor's 2nd parameter i.e. `network` is set to [env.network](https://github.com/wighawag/hardhat-deploy/blob/3d08a33a6ae9404bf56187c4f49ec359427672eb/src/index.ts#L271) i.e.   `hre.network`. Potentially have `hedera-hardhat-hethers` plugin load `network: Network` into `hre` with a compatible `Provider`

**Comment by natanasow** [comment]
Hi, @mshakeg,

The `hardhat-deploy` plugin, under the hood, uses `etherjs` and the `etherjs` provider (i.e. JSON RPC). On the other side, `hethers` doesn't implement the JSON RPC provider, so you can't use `hardhat-deploy` with `hardhat-hethers` out of the box. To use `hardhat-deploy` with `hethers`, we have to develop a `hardhat-deploy-hedera` plugin which core will interact with `hethers` instead of `ethers`.

Alternatively, you can use [the hedera JSON RPC relay](https://github.com/hashgraph/hedera-json-rpc-relay) with ethers. That will fix most of your issues, and you will be able to interact `hardhat-deploy` without any concerns.

**Comment by natanasow** [comment]
Yeah, each plugin that uses `ethersjs` will not work correctly and must be rewritten with `hethersjs`.
